RDKBDEV-2988: Fix memory leaks in "zilker-sdk"
rdkcentral/zilker-sdk pull request #7
Opened 2024-11-05 06:39 UTC by mtomczykmobica

Reason for change: Fix memory leaks related to the usage of cJSON_Parse and cJSONPrint.
Test Procedure: Expected result - No memory leaks for cJSON_Parse and cJSONPrint..
Risks: Low

Change-Id: I6ad590f595aa6fca30c0fdc444c4b4052b7a8b16

2024-11-05 06:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/zilker-sdk?pullRequest=7) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/zilker-sdk?pullRequest=7) before we can accept your contribution.<br/><hr/>**Marcin Tomczyk** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/zilker-sdk?pullRequest=7) it.</sub>

2024-11-05 13:32 UTC, pradeeptakdas commented
Hi @mtomczykmobica 
Can you sign the CLA?

2024-11-05 14:10 UTC, mtomczykmobica commented
> Hi @mtomczykmobica Can you sign the CLA?

Done

2024-11-18 14:39 UTC, mkkoch requested changes

2024-11-18 14:39 UTC, mkkoch commented on source/libs/cslt/src/sheens/sheens_transcoder_triggers.c
> +            free(whenTimeJs);
The AUTO_CLEAN(free_generic__auto) takes care of releasing the values upon return so this will in fact cause a double free.

2024-11-18 14:39 UTC, mkkoch commented on source/libs/cslt/src/sheens/sheens_transcoder_triggers.c
> +        free(endTimeJs);
Same as above, these are covered by the AUTO_CLEAN(free_generic__auto).

2024-11-18 14:39 UTC, mkkoch commented on source/libs/cslt/src/sheens/sheens_transcoder_triggers.c
> +    free(whenTimeJs);
Same here

2024-11-18 14:39 UTC, mkkoch commented on source/libs/cslt/src/sheens/sheens_transcoder_triggers.c
> +    free(js);
Same here

2024-11-18 14:39 UTC, mkkoch commented on source/services/rdkIntegration/src/parodus_interface.c
> +            free(notifyPayloadString);
This is freed blow and there is no returns before that free so this introduces a double free.

2024-11-19 06:18 UTC, mtomczykmobica commented on source/libs/cslt/src/sheens/sheens_transcoder_triggers.c
> +            free(whenTimeJs);
Done

2024-11-19 06:19 UTC, mtomczykmobica commented on source/libs/cslt/src/sheens/sheens_transcoder_triggers.c
> +        free(endTimeJs);
Done

2024-11-19 06:21 UTC, mtomczykmobica commented on source/libs/cslt/src/sheens/sheens_transcoder_triggers.c
> +    free(whenTimeJs);
Done

2024-11-19 06:24 UTC, mtomczykmobica commented on source/libs/cslt/src/sheens/sheens_transcoder_triggers.c
> +    free(js);
Done

2024-11-19 06:27 UTC, mtomczykmobica commented on source/services/rdkIntegration/src/parodus_interface.c
> +            free(notifyPayloadString);
Done

2024-11-19 06:30 UTC, closed without merging

2024-11-19 07:13 UTC, mtomczykmobica reviewed
New merge request: https://github.com/rdkcentral/zilker-sdk/pull/8